/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIdRouteRouteImport } from './routes/$appId/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AppIdIndexRouteImport } from './routes/$appId/index'
import { Route as AppIdSplatRouteImport } from './routes/$appId/$'
import { Route as AppIdExampleRouteRouteImport } from './routes/$appId/example/route'
import { Route as AppIdSystemRouteRouteImport } from './routes/$appId/system/route'
import { Route as AppIdSphereRouteRouteImport } from './routes/$appId_.sphere/route'
import { Route as AuthForgotEmailRouteImport } from './routes/_auth/forgot-email'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSplatRouteImport } from './routes/_main/$'
import { Route as MainSelectAppRouteImport } from './routes/_main/select-app'
import { Route as MainSettingsRouteRouteImport } from './routes/_main/settings/route'
import { Route as AppIdExampleIndexRouteImport } from './routes/$appId/example/index'
import { Route as AppIdHomeIndexRouteImport } from './routes/$appId/home/index'
import { Route as AppIdSystemIndexRouteImport } from './routes/$appId/system/index'
import { Route as AppIdSystemDataDictRouteRouteImport } from './routes/$appId/system/data-dict/route'
import { Route as AppIdSystemMenusRouteRouteImport } from './routes/$appId/system/menus/route'
import { Route as AppIdSystemRolesRouteRouteImport } from './routes/$appId/system/roles/route'
import { Route as AppIdSphereIndexRouteImport } from './routes/$appId_.sphere/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainSettingsAIRouteImport } from './routes/_main/settings/AI'
import { Route as MainSettingsAboutRouteImport } from './routes/_main/settings/about'
import { Route as MainSettingsAppearanceRouteImport } from './routes/_main/settings/appearance'
import { Route as MainSettingsProfileRouteImport } from './routes/_main/settings/profile'
import { Route as AppIdExampleComplexTableIndexRouteImport } from './routes/$appId/example/complex-table/index'
import { Route as AppIdExampleTableIndexRouteImport } from './routes/$appId/example/table/index'
import { Route as AppIdExampleTableIdRouteImport } from './routes/$appId/example/table/$id'
import { Route as AppIdExampleTableNewRouteImport } from './routes/$appId/example/table/new'
import { Route as AppIdExampleTicketsIndexRouteImport } from './routes/$appId/example/tickets/index'
import { Route as AppIdExampleTicketsNewRouteImport } from './routes/$appId/example/tickets/new'
import { Route as AppIdExampleTreeTableIndexRouteImport } from './routes/$appId/example/tree-table/index'
import { Route as AppIdSystemDataDictIndexRouteImport } from './routes/$appId/system/data-dict/index'
import { Route as AppIdSystemDataDictTypeIdRouteImport } from './routes/$appId/system/data-dict/$typeId'
import { Route as AppIdSystemMenusIndexRouteImport } from './routes/$appId/system/menus/index'
import { Route as AppIdSystemMenusFeatureIdRouteImport } from './routes/$appId/system/menus/$featureId'
import { Route as AppIdSystemMenusNewRouteImport } from './routes/$appId/system/menus/new'
import { Route as AppIdSystemRolesIndexRouteImport } from './routes/$appId/system/roles/index'
import { Route as AppIdSystemRolesRoleIdRouteImport } from './routes/$appId/system/roles/$roleId'
import { Route as AppIdSphereChatChatIdRouteImport } from './routes/$appId_.sphere/chat/$chatId'
import { Route as AuthOauthProviderCallbackRouteImport } from './routes/_auth/oauth/$provider/callback'
import { Route as AppIdExampleTableIdEditRouteImport } from './routes/$appId/example/table/$id.edit'
import { Route as AppIdExampleTicketsIdEditRouteImport } from './routes/$appId/example/tickets/$id.edit'

const AppIdRouteRoute = AppIdRouteRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdIndexRoute = AppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdSplatRoute = AppIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdExampleRouteRoute = AppIdExampleRouteRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdSystemRouteRoute = AppIdSystemRouteRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdSphereRouteRoute = AppIdSphereRouteRouteImport.update({
  id: '/$appId_/sphere',
  path: '/$appId/sphere',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotEmailRoute = AuthForgotEmailRouteImport.update({
  id: '/forgot-email',
  path: '/forgot-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSplatRoute = MainSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSelectAppRoute = MainSelectAppRouteImport.update({
  id: '/select-app',
  path: '/select-app',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRouteRoute = MainSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const AppIdExampleIndexRoute = AppIdExampleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdExampleRouteRoute,
} as any)
const AppIdHomeIndexRoute = AppIdHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdSystemIndexRoute = AppIdSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdSystemRouteRoute,
} as any)
const AppIdSystemDataDictRouteRoute =
  AppIdSystemDataDictRouteRouteImport.update({
    id: '/data-dict',
    path: '/data-dict',
    getParentRoute: () => AppIdSystemRouteRoute,
  } as any)
const AppIdSystemMenusRouteRoute = AppIdSystemMenusRouteRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppIdSystemRouteRoute,
} as any)
const AppIdSystemRolesRouteRoute = AppIdSystemRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppIdSystemRouteRoute,
} as any)
const AppIdSphereIndexRoute = AppIdSphereIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdSphereRouteRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const MainSettingsAIRoute = MainSettingsAIRouteImport.update({
  id: '/AI',
  path: '/AI',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const MainSettingsAboutRoute = MainSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const MainSettingsAppearanceRoute = MainSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const MainSettingsProfileRoute = MainSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const AppIdExampleComplexTableIndexRoute =
  AppIdExampleComplexTableIndexRouteImport.update({
    id: '/complex-table/',
    path: '/complex-table/',
    getParentRoute: () => AppIdExampleRouteRoute,
  } as any)
const AppIdExampleTableIndexRoute = AppIdExampleTableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => AppIdExampleRouteRoute,
} as any)
const AppIdExampleTableIdRoute = AppIdExampleTableIdRouteImport.update({
  id: '/table/$id',
  path: '/table/$id',
  getParentRoute: () => AppIdExampleRouteRoute,
} as any)
const AppIdExampleTableNewRoute = AppIdExampleTableNewRouteImport.update({
  id: '/table/new',
  path: '/table/new',
  getParentRoute: () => AppIdExampleRouteRoute,
} as any)
const AppIdExampleTicketsIndexRoute =
  AppIdExampleTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AppIdExampleRouteRoute,
  } as any)
const AppIdExampleTicketsNewRoute = AppIdExampleTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => AppIdExampleRouteRoute,
} as any)
const AppIdExampleTreeTableIndexRoute =
  AppIdExampleTreeTableIndexRouteImport.update({
    id: '/tree-table/',
    path: '/tree-table/',
    getParentRoute: () => AppIdExampleRouteRoute,
  } as any)
const AppIdSystemDataDictIndexRoute =
  AppIdSystemDataDictIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppIdSystemDataDictRouteRoute,
  } as any)
const AppIdSystemDataDictTypeIdRoute =
  AppIdSystemDataDictTypeIdRouteImport.update({
    id: '/$typeId',
    path: '/$typeId',
    getParentRoute: () => AppIdSystemDataDictRouteRoute,
  } as any)
const AppIdSystemMenusIndexRoute = AppIdSystemMenusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdSystemMenusRouteRoute,
} as any)
const AppIdSystemMenusFeatureIdRoute =
  AppIdSystemMenusFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => AppIdSystemMenusRouteRoute,
  } as any)
const AppIdSystemMenusNewRoute = AppIdSystemMenusNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppIdSystemMenusRouteRoute,
} as any)
const AppIdSystemRolesIndexRoute = AppIdSystemRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdSystemRolesRouteRoute,
} as any)
const AppIdSystemRolesRoleIdRoute = AppIdSystemRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AppIdSystemRolesRouteRoute,
} as any)
const AppIdSphereChatChatIdRoute = AppIdSphereChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppIdSphereRouteRoute,
} as any)
const AuthOauthProviderCallbackRoute =
  AuthOauthProviderCallbackRouteImport.update({
    id: '/oauth/$provider/callback',
    path: '/oauth/$provider/callback',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AppIdExampleTableIdEditRoute = AppIdExampleTableIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppIdExampleTableIdRoute,
} as any)
const AppIdExampleTicketsIdEditRoute =
  AppIdExampleTicketsIdEditRouteImport.update({
    id: '/tickets/$id/edit',
    path: '/tickets/$id/edit',
    getParentRoute: () => AppIdExampleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$appId': typeof AppIdRouteRouteWithChildren
  '/': typeof MainIndexRoute
  '/$appId/example': typeof AppIdExampleRouteRouteWithChildren
  '/$appId/system': typeof AppIdSystemRouteRouteWithChildren
  '/$appId/sphere': typeof AppIdSphereRouteRouteWithChildren
  '/settings': typeof MainSettingsRouteRouteWithChildren
  '/$appId/$': typeof AppIdSplatRoute
  '/forgot-email': typeof AuthForgotEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$': typeof MainSplatRoute
  '/select-app': typeof MainSelectAppRoute
  '/$appId/': typeof AppIdIndexRoute
  '/$appId/system/data-dict': typeof AppIdSystemDataDictRouteRouteWithChildren
  '/$appId/system/menus': typeof AppIdSystemMenusRouteRouteWithChildren
  '/$appId/system/roles': typeof AppIdSystemRolesRouteRouteWithChildren
  '/settings/AI': typeof MainSettingsAIRoute
  '/settings/about': typeof MainSettingsAboutRoute
  '/settings/appearance': typeof MainSettingsAppearanceRoute
  '/settings/profile': typeof MainSettingsProfileRoute
  '/$appId/example/': typeof AppIdExampleIndexRoute
  '/$appId/home/': typeof AppIdHomeIndexRoute
  '/$appId/system/': typeof AppIdSystemIndexRoute
  '/$appId/sphere/': typeof AppIdSphereIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/$appId/example/table/$id': typeof AppIdExampleTableIdRouteWithChildren
  '/$appId/example/table/new': typeof AppIdExampleTableNewRoute
  '/$appId/example/tickets/new': typeof AppIdExampleTicketsNewRoute
  '/$appId/system/data-dict/$typeId': typeof AppIdSystemDataDictTypeIdRoute
  '/$appId/system/menus/$featureId': typeof AppIdSystemMenusFeatureIdRoute
  '/$appId/system/menus/new': typeof AppIdSystemMenusNewRoute
  '/$appId/system/roles/$roleId': typeof AppIdSystemRolesRoleIdRoute
  '/$appId/sphere/chat/$chatId': typeof AppIdSphereChatChatIdRoute
  '/oauth/$provider/callback': typeof AuthOauthProviderCallbackRoute
  '/$appId/example/complex-table/': typeof AppIdExampleComplexTableIndexRoute
  '/$appId/example/table/': typeof AppIdExampleTableIndexRoute
  '/$appId/example/tickets/': typeof AppIdExampleTicketsIndexRoute
  '/$appId/example/tree-table/': typeof AppIdExampleTreeTableIndexRoute
  '/$appId/system/data-dict/': typeof AppIdSystemDataDictIndexRoute
  '/$appId/system/menus/': typeof AppIdSystemMenusIndexRoute
  '/$appId/system/roles/': typeof AppIdSystemRolesIndexRoute
  '/$appId/example/table/$id/edit': typeof AppIdExampleTableIdEditRoute
  '/$appId/example/tickets/$id/edit': typeof AppIdExampleTicketsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/$appId/$': typeof AppIdSplatRoute
  '/forgot-email': typeof AuthForgotEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$': typeof MainSplatRoute
  '/select-app': typeof MainSelectAppRoute
  '/$appId': typeof AppIdIndexRoute
  '/settings/AI': typeof MainSettingsAIRoute
  '/settings/about': typeof MainSettingsAboutRoute
  '/settings/appearance': typeof MainSettingsAppearanceRoute
  '/settings/profile': typeof MainSettingsProfileRoute
  '/$appId/example': typeof AppIdExampleIndexRoute
  '/$appId/home': typeof AppIdHomeIndexRoute
  '/$appId/system': typeof AppIdSystemIndexRoute
  '/$appId/sphere': typeof AppIdSphereIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/$appId/example/table/$id': typeof AppIdExampleTableIdRouteWithChildren
  '/$appId/example/table/new': typeof AppIdExampleTableNewRoute
  '/$appId/example/tickets/new': typeof AppIdExampleTicketsNewRoute
  '/$appId/system/data-dict/$typeId': typeof AppIdSystemDataDictTypeIdRoute
  '/$appId/system/menus/$featureId': typeof AppIdSystemMenusFeatureIdRoute
  '/$appId/system/menus/new': typeof AppIdSystemMenusNewRoute
  '/$appId/system/roles/$roleId': typeof AppIdSystemRolesRoleIdRoute
  '/$appId/sphere/chat/$chatId': typeof AppIdSphereChatChatIdRoute
  '/oauth/$provider/callback': typeof AuthOauthProviderCallbackRoute
  '/$appId/example/complex-table': typeof AppIdExampleComplexTableIndexRoute
  '/$appId/example/table': typeof AppIdExampleTableIndexRoute
  '/$appId/example/tickets': typeof AppIdExampleTicketsIndexRoute
  '/$appId/example/tree-table': typeof AppIdExampleTreeTableIndexRoute
  '/$appId/system/data-dict': typeof AppIdSystemDataDictIndexRoute
  '/$appId/system/menus': typeof AppIdSystemMenusIndexRoute
  '/$appId/system/roles': typeof AppIdSystemRolesIndexRoute
  '/$appId/example/table/$id/edit': typeof AppIdExampleTableIdEditRoute
  '/$appId/example/tickets/$id/edit': typeof AppIdExampleTicketsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$appId': typeof AppIdRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/$appId/example': typeof AppIdExampleRouteRouteWithChildren
  '/$appId/system': typeof AppIdSystemRouteRouteWithChildren
  '/$appId_/sphere': typeof AppIdSphereRouteRouteWithChildren
  '/_main/settings': typeof MainSettingsRouteRouteWithChildren
  '/$appId/$': typeof AppIdSplatRoute
  '/_auth/forgot-email': typeof AuthForgotEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/$': typeof MainSplatRoute
  '/_main/select-app': typeof MainSelectAppRoute
  '/$appId/': typeof AppIdIndexRoute
  '/_main/': typeof MainIndexRoute
  '/$appId/system/data-dict': typeof AppIdSystemDataDictRouteRouteWithChildren
  '/$appId/system/menus': typeof AppIdSystemMenusRouteRouteWithChildren
  '/$appId/system/roles': typeof AppIdSystemRolesRouteRouteWithChildren
  '/_main/settings/AI': typeof MainSettingsAIRoute
  '/_main/settings/about': typeof MainSettingsAboutRoute
  '/_main/settings/appearance': typeof MainSettingsAppearanceRoute
  '/_main/settings/profile': typeof MainSettingsProfileRoute
  '/$appId/example/': typeof AppIdExampleIndexRoute
  '/$appId/home/': typeof AppIdHomeIndexRoute
  '/$appId/system/': typeof AppIdSystemIndexRoute
  '/$appId_/sphere/': typeof AppIdSphereIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/$appId/example/table/$id': typeof AppIdExampleTableIdRouteWithChildren
  '/$appId/example/table/new': typeof AppIdExampleTableNewRoute
  '/$appId/example/tickets/new': typeof AppIdExampleTicketsNewRoute
  '/$appId/system/data-dict/$typeId': typeof AppIdSystemDataDictTypeIdRoute
  '/$appId/system/menus/$featureId': typeof AppIdSystemMenusFeatureIdRoute
  '/$appId/system/menus/new': typeof AppIdSystemMenusNewRoute
  '/$appId/system/roles/$roleId': typeof AppIdSystemRolesRoleIdRoute
  '/$appId_/sphere/chat/$chatId': typeof AppIdSphereChatChatIdRoute
  '/_auth/oauth/$provider/callback': typeof AuthOauthProviderCallbackRoute
  '/$appId/example/complex-table/': typeof AppIdExampleComplexTableIndexRoute
  '/$appId/example/table/': typeof AppIdExampleTableIndexRoute
  '/$appId/example/tickets/': typeof AppIdExampleTicketsIndexRoute
  '/$appId/example/tree-table/': typeof AppIdExampleTreeTableIndexRoute
  '/$appId/system/data-dict/': typeof AppIdSystemDataDictIndexRoute
  '/$appId/system/menus/': typeof AppIdSystemMenusIndexRoute
  '/$appId/system/roles/': typeof AppIdSystemRolesIndexRoute
  '/$appId/example/table/$id/edit': typeof AppIdExampleTableIdEditRoute
  '/$appId/example/tickets/$id/edit': typeof AppIdExampleTicketsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$appId'
    | '/'
    | '/$appId/example'
    | '/$appId/system'
    | '/$appId/sphere'
    | '/settings'
    | '/$appId/$'
    | '/forgot-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/$'
    | '/select-app'
    | '/$appId/'
    | '/$appId/system/data-dict'
    | '/$appId/system/menus'
    | '/$appId/system/roles'
    | '/settings/AI'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/profile'
    | '/$appId/example/'
    | '/$appId/home/'
    | '/$appId/system/'
    | '/$appId/sphere/'
    | '/settings/'
    | '/$appId/example/table/$id'
    | '/$appId/example/table/new'
    | '/$appId/example/tickets/new'
    | '/$appId/system/data-dict/$typeId'
    | '/$appId/system/menus/$featureId'
    | '/$appId/system/menus/new'
    | '/$appId/system/roles/$roleId'
    | '/$appId/sphere/chat/$chatId'
    | '/oauth/$provider/callback'
    | '/$appId/example/complex-table/'
    | '/$appId/example/table/'
    | '/$appId/example/tickets/'
    | '/$appId/example/tree-table/'
    | '/$appId/system/data-dict/'
    | '/$appId/system/menus/'
    | '/$appId/system/roles/'
    | '/$appId/example/table/$id/edit'
    | '/$appId/example/tickets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$appId/$'
    | '/forgot-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/$'
    | '/select-app'
    | '/$appId'
    | '/settings/AI'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/profile'
    | '/$appId/example'
    | '/$appId/home'
    | '/$appId/system'
    | '/$appId/sphere'
    | '/settings'
    | '/$appId/example/table/$id'
    | '/$appId/example/table/new'
    | '/$appId/example/tickets/new'
    | '/$appId/system/data-dict/$typeId'
    | '/$appId/system/menus/$featureId'
    | '/$appId/system/menus/new'
    | '/$appId/system/roles/$roleId'
    | '/$appId/sphere/chat/$chatId'
    | '/oauth/$provider/callback'
    | '/$appId/example/complex-table'
    | '/$appId/example/table'
    | '/$appId/example/tickets'
    | '/$appId/example/tree-table'
    | '/$appId/system/data-dict'
    | '/$appId/system/menus'
    | '/$appId/system/roles'
    | '/$appId/example/table/$id/edit'
    | '/$appId/example/tickets/$id/edit'
  id:
    | '__root__'
    | '/$appId'
    | '/_auth'
    | '/_main'
    | '/$appId/example'
    | '/$appId/system'
    | '/$appId_/sphere'
    | '/_main/settings'
    | '/$appId/$'
    | '/_auth/forgot-email'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/$'
    | '/_main/select-app'
    | '/$appId/'
    | '/_main/'
    | '/$appId/system/data-dict'
    | '/$appId/system/menus'
    | '/$appId/system/roles'
    | '/_main/settings/AI'
    | '/_main/settings/about'
    | '/_main/settings/appearance'
    | '/_main/settings/profile'
    | '/$appId/example/'
    | '/$appId/home/'
    | '/$appId/system/'
    | '/$appId_/sphere/'
    | '/_main/settings/'
    | '/$appId/example/table/$id'
    | '/$appId/example/table/new'
    | '/$appId/example/tickets/new'
    | '/$appId/system/data-dict/$typeId'
    | '/$appId/system/menus/$featureId'
    | '/$appId/system/menus/new'
    | '/$appId/system/roles/$roleId'
    | '/$appId_/sphere/chat/$chatId'
    | '/_auth/oauth/$provider/callback'
    | '/$appId/example/complex-table/'
    | '/$appId/example/table/'
    | '/$appId/example/tickets/'
    | '/$appId/example/tree-table/'
    | '/$appId/system/data-dict/'
    | '/$appId/system/menus/'
    | '/$appId/system/roles/'
    | '/$appId/example/table/$id/edit'
    | '/$appId/example/tickets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIdRouteRoute: typeof AppIdRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AppIdSphereRouteRoute: typeof AppIdSphereRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$appId': {
      id: '/$appId'
      path: '/$appId'
      fullPath: '/$appId'
      preLoaderRoute: typeof AppIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$appId/': {
      id: '/$appId/'
      path: '/'
      fullPath: '/$appId/'
      preLoaderRoute: typeof AppIdIndexRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/$appId/$': {
      id: '/$appId/$'
      path: '/$'
      fullPath: '/$appId/$'
      preLoaderRoute: typeof AppIdSplatRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/$appId/example': {
      id: '/$appId/example'
      path: '/example'
      fullPath: '/$appId/example'
      preLoaderRoute: typeof AppIdExampleRouteRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/$appId/system': {
      id: '/$appId/system'
      path: '/system'
      fullPath: '/$appId/system'
      preLoaderRoute: typeof AppIdSystemRouteRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/$appId_/sphere': {
      id: '/$appId_/sphere'
      path: '/$appId/sphere'
      fullPath: '/$appId/sphere'
      preLoaderRoute: typeof AppIdSphereRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-email': {
      id: '/_auth/forgot-email'
      path: '/forgot-email'
      fullPath: '/forgot-email'
      preLoaderRoute: typeof AuthForgotEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/$': {
      id: '/_main/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof MainSplatRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/select-app': {
      id: '/_main/select-app'
      path: '/select-app'
      fullPath: '/select-app'
      preLoaderRoute: typeof MainSelectAppRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$appId/example/': {
      id: '/$appId/example/'
      path: '/'
      fullPath: '/$appId/example/'
      preLoaderRoute: typeof AppIdExampleIndexRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/home/': {
      id: '/$appId/home/'
      path: '/home'
      fullPath: '/$appId/home/'
      preLoaderRoute: typeof AppIdHomeIndexRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/$appId/system/': {
      id: '/$appId/system/'
      path: '/'
      fullPath: '/$appId/system/'
      preLoaderRoute: typeof AppIdSystemIndexRouteImport
      parentRoute: typeof AppIdSystemRouteRoute
    }
    '/$appId/system/data-dict': {
      id: '/$appId/system/data-dict'
      path: '/data-dict'
      fullPath: '/$appId/system/data-dict'
      preLoaderRoute: typeof AppIdSystemDataDictRouteRouteImport
      parentRoute: typeof AppIdSystemRouteRoute
    }
    '/$appId/system/menus': {
      id: '/$appId/system/menus'
      path: '/menus'
      fullPath: '/$appId/system/menus'
      preLoaderRoute: typeof AppIdSystemMenusRouteRouteImport
      parentRoute: typeof AppIdSystemRouteRoute
    }
    '/$appId/system/roles': {
      id: '/$appId/system/roles'
      path: '/roles'
      fullPath: '/$appId/system/roles'
      preLoaderRoute: typeof AppIdSystemRolesRouteRouteImport
      parentRoute: typeof AppIdSystemRouteRoute
    }
    '/$appId_/sphere/': {
      id: '/$appId_/sphere/'
      path: '/'
      fullPath: '/$appId/sphere/'
      preLoaderRoute: typeof AppIdSphereIndexRouteImport
      parentRoute: typeof AppIdSphereRouteRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/_main/settings/AI': {
      id: '/_main/settings/AI'
      path: '/AI'
      fullPath: '/settings/AI'
      preLoaderRoute: typeof MainSettingsAIRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/_main/settings/about': {
      id: '/_main/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof MainSettingsAboutRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/_main/settings/appearance': {
      id: '/_main/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof MainSettingsAppearanceRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/_main/settings/profile': {
      id: '/_main/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof MainSettingsProfileRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/$appId/example/complex-table/': {
      id: '/$appId/example/complex-table/'
      path: '/complex-table'
      fullPath: '/$appId/example/complex-table/'
      preLoaderRoute: typeof AppIdExampleComplexTableIndexRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/example/table/': {
      id: '/$appId/example/table/'
      path: '/table'
      fullPath: '/$appId/example/table/'
      preLoaderRoute: typeof AppIdExampleTableIndexRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/example/table/$id': {
      id: '/$appId/example/table/$id'
      path: '/table/$id'
      fullPath: '/$appId/example/table/$id'
      preLoaderRoute: typeof AppIdExampleTableIdRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/example/table/new': {
      id: '/$appId/example/table/new'
      path: '/table/new'
      fullPath: '/$appId/example/table/new'
      preLoaderRoute: typeof AppIdExampleTableNewRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/example/tickets/': {
      id: '/$appId/example/tickets/'
      path: '/tickets'
      fullPath: '/$appId/example/tickets/'
      preLoaderRoute: typeof AppIdExampleTicketsIndexRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/example/tickets/new': {
      id: '/$appId/example/tickets/new'
      path: '/tickets/new'
      fullPath: '/$appId/example/tickets/new'
      preLoaderRoute: typeof AppIdExampleTicketsNewRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/example/tree-table/': {
      id: '/$appId/example/tree-table/'
      path: '/tree-table'
      fullPath: '/$appId/example/tree-table/'
      preLoaderRoute: typeof AppIdExampleTreeTableIndexRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
    '/$appId/system/data-dict/': {
      id: '/$appId/system/data-dict/'
      path: '/'
      fullPath: '/$appId/system/data-dict/'
      preLoaderRoute: typeof AppIdSystemDataDictIndexRouteImport
      parentRoute: typeof AppIdSystemDataDictRouteRoute
    }
    '/$appId/system/data-dict/$typeId': {
      id: '/$appId/system/data-dict/$typeId'
      path: '/$typeId'
      fullPath: '/$appId/system/data-dict/$typeId'
      preLoaderRoute: typeof AppIdSystemDataDictTypeIdRouteImport
      parentRoute: typeof AppIdSystemDataDictRouteRoute
    }
    '/$appId/system/menus/': {
      id: '/$appId/system/menus/'
      path: '/'
      fullPath: '/$appId/system/menus/'
      preLoaderRoute: typeof AppIdSystemMenusIndexRouteImport
      parentRoute: typeof AppIdSystemMenusRouteRoute
    }
    '/$appId/system/menus/$featureId': {
      id: '/$appId/system/menus/$featureId'
      path: '/$featureId'
      fullPath: '/$appId/system/menus/$featureId'
      preLoaderRoute: typeof AppIdSystemMenusFeatureIdRouteImport
      parentRoute: typeof AppIdSystemMenusRouteRoute
    }
    '/$appId/system/menus/new': {
      id: '/$appId/system/menus/new'
      path: '/new'
      fullPath: '/$appId/system/menus/new'
      preLoaderRoute: typeof AppIdSystemMenusNewRouteImport
      parentRoute: typeof AppIdSystemMenusRouteRoute
    }
    '/$appId/system/roles/': {
      id: '/$appId/system/roles/'
      path: '/'
      fullPath: '/$appId/system/roles/'
      preLoaderRoute: typeof AppIdSystemRolesIndexRouteImport
      parentRoute: typeof AppIdSystemRolesRouteRoute
    }
    '/$appId/system/roles/$roleId': {
      id: '/$appId/system/roles/$roleId'
      path: '/$roleId'
      fullPath: '/$appId/system/roles/$roleId'
      preLoaderRoute: typeof AppIdSystemRolesRoleIdRouteImport
      parentRoute: typeof AppIdSystemRolesRouteRoute
    }
    '/$appId_/sphere/chat/$chatId': {
      id: '/$appId_/sphere/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/$appId/sphere/chat/$chatId'
      preLoaderRoute: typeof AppIdSphereChatChatIdRouteImport
      parentRoute: typeof AppIdSphereRouteRoute
    }
    '/_auth/oauth/$provider/callback': {
      id: '/_auth/oauth/$provider/callback'
      path: '/oauth/$provider/callback'
      fullPath: '/oauth/$provider/callback'
      preLoaderRoute: typeof AuthOauthProviderCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$appId/example/table/$id/edit': {
      id: '/$appId/example/table/$id/edit'
      path: '/edit'
      fullPath: '/$appId/example/table/$id/edit'
      preLoaderRoute: typeof AppIdExampleTableIdEditRouteImport
      parentRoute: typeof AppIdExampleTableIdRoute
    }
    '/$appId/example/tickets/$id/edit': {
      id: '/$appId/example/tickets/$id/edit'
      path: '/tickets/$id/edit'
      fullPath: '/$appId/example/tickets/$id/edit'
      preLoaderRoute: typeof AppIdExampleTicketsIdEditRouteImport
      parentRoute: typeof AppIdExampleRouteRoute
    }
  }
}

interface AppIdExampleTableIdRouteChildren {
  AppIdExampleTableIdEditRoute: typeof AppIdExampleTableIdEditRoute
}

const AppIdExampleTableIdRouteChildren: AppIdExampleTableIdRouteChildren = {
  AppIdExampleTableIdEditRoute: AppIdExampleTableIdEditRoute,
}

const AppIdExampleTableIdRouteWithChildren =
  AppIdExampleTableIdRoute._addFileChildren(AppIdExampleTableIdRouteChildren)

interface AppIdExampleRouteRouteChildren {
  AppIdExampleIndexRoute: typeof AppIdExampleIndexRoute
  AppIdExampleTableIdRoute: typeof AppIdExampleTableIdRouteWithChildren
  AppIdExampleTableNewRoute: typeof AppIdExampleTableNewRoute
  AppIdExampleTicketsNewRoute: typeof AppIdExampleTicketsNewRoute
  AppIdExampleComplexTableIndexRoute: typeof AppIdExampleComplexTableIndexRoute
  AppIdExampleTableIndexRoute: typeof AppIdExampleTableIndexRoute
  AppIdExampleTicketsIndexRoute: typeof AppIdExampleTicketsIndexRoute
  AppIdExampleTreeTableIndexRoute: typeof AppIdExampleTreeTableIndexRoute
  AppIdExampleTicketsIdEditRoute: typeof AppIdExampleTicketsIdEditRoute
}

const AppIdExampleRouteRouteChildren: AppIdExampleRouteRouteChildren = {
  AppIdExampleIndexRoute: AppIdExampleIndexRoute,
  AppIdExampleTableIdRoute: AppIdExampleTableIdRouteWithChildren,
  AppIdExampleTableNewRoute: AppIdExampleTableNewRoute,
  AppIdExampleTicketsNewRoute: AppIdExampleTicketsNewRoute,
  AppIdExampleComplexTableIndexRoute: AppIdExampleComplexTableIndexRoute,
  AppIdExampleTableIndexRoute: AppIdExampleTableIndexRoute,
  AppIdExampleTicketsIndexRoute: AppIdExampleTicketsIndexRoute,
  AppIdExampleTreeTableIndexRoute: AppIdExampleTreeTableIndexRoute,
  AppIdExampleTicketsIdEditRoute: AppIdExampleTicketsIdEditRoute,
}

const AppIdExampleRouteRouteWithChildren =
  AppIdExampleRouteRoute._addFileChildren(AppIdExampleRouteRouteChildren)

interface AppIdSystemDataDictRouteRouteChildren {
  AppIdSystemDataDictTypeIdRoute: typeof AppIdSystemDataDictTypeIdRoute
  AppIdSystemDataDictIndexRoute: typeof AppIdSystemDataDictIndexRoute
}

const AppIdSystemDataDictRouteRouteChildren: AppIdSystemDataDictRouteRouteChildren =
  {
    AppIdSystemDataDictTypeIdRoute: AppIdSystemDataDictTypeIdRoute,
    AppIdSystemDataDictIndexRoute: AppIdSystemDataDictIndexRoute,
  }

const AppIdSystemDataDictRouteRouteWithChildren =
  AppIdSystemDataDictRouteRoute._addFileChildren(
    AppIdSystemDataDictRouteRouteChildren,
  )

interface AppIdSystemMenusRouteRouteChildren {
  AppIdSystemMenusFeatureIdRoute: typeof AppIdSystemMenusFeatureIdRoute
  AppIdSystemMenusNewRoute: typeof AppIdSystemMenusNewRoute
  AppIdSystemMenusIndexRoute: typeof AppIdSystemMenusIndexRoute
}

const AppIdSystemMenusRouteRouteChildren: AppIdSystemMenusRouteRouteChildren = {
  AppIdSystemMenusFeatureIdRoute: AppIdSystemMenusFeatureIdRoute,
  AppIdSystemMenusNewRoute: AppIdSystemMenusNewRoute,
  AppIdSystemMenusIndexRoute: AppIdSystemMenusIndexRoute,
}

const AppIdSystemMenusRouteRouteWithChildren =
  AppIdSystemMenusRouteRoute._addFileChildren(
    AppIdSystemMenusRouteRouteChildren,
  )

interface AppIdSystemRolesRouteRouteChildren {
  AppIdSystemRolesRoleIdRoute: typeof AppIdSystemRolesRoleIdRoute
  AppIdSystemRolesIndexRoute: typeof AppIdSystemRolesIndexRoute
}

const AppIdSystemRolesRouteRouteChildren: AppIdSystemRolesRouteRouteChildren = {
  AppIdSystemRolesRoleIdRoute: AppIdSystemRolesRoleIdRoute,
  AppIdSystemRolesIndexRoute: AppIdSystemRolesIndexRoute,
}

const AppIdSystemRolesRouteRouteWithChildren =
  AppIdSystemRolesRouteRoute._addFileChildren(
    AppIdSystemRolesRouteRouteChildren,
  )

interface AppIdSystemRouteRouteChildren {
  AppIdSystemDataDictRouteRoute: typeof AppIdSystemDataDictRouteRouteWithChildren
  AppIdSystemMenusRouteRoute: typeof AppIdSystemMenusRouteRouteWithChildren
  AppIdSystemRolesRouteRoute: typeof AppIdSystemRolesRouteRouteWithChildren
  AppIdSystemIndexRoute: typeof AppIdSystemIndexRoute
}

const AppIdSystemRouteRouteChildren: AppIdSystemRouteRouteChildren = {
  AppIdSystemDataDictRouteRoute: AppIdSystemDataDictRouteRouteWithChildren,
  AppIdSystemMenusRouteRoute: AppIdSystemMenusRouteRouteWithChildren,
  AppIdSystemRolesRouteRoute: AppIdSystemRolesRouteRouteWithChildren,
  AppIdSystemIndexRoute: AppIdSystemIndexRoute,
}

const AppIdSystemRouteRouteWithChildren =
  AppIdSystemRouteRoute._addFileChildren(AppIdSystemRouteRouteChildren)

interface AppIdRouteRouteChildren {
  AppIdExampleRouteRoute: typeof AppIdExampleRouteRouteWithChildren
  AppIdSystemRouteRoute: typeof AppIdSystemRouteRouteWithChildren
  AppIdSplatRoute: typeof AppIdSplatRoute
  AppIdIndexRoute: typeof AppIdIndexRoute
  AppIdHomeIndexRoute: typeof AppIdHomeIndexRoute
}

const AppIdRouteRouteChildren: AppIdRouteRouteChildren = {
  AppIdExampleRouteRoute: AppIdExampleRouteRouteWithChildren,
  AppIdSystemRouteRoute: AppIdSystemRouteRouteWithChildren,
  AppIdSplatRoute: AppIdSplatRoute,
  AppIdIndexRoute: AppIdIndexRoute,
  AppIdHomeIndexRoute: AppIdHomeIndexRoute,
}

const AppIdRouteRouteWithChildren = AppIdRouteRoute._addFileChildren(
  AppIdRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotEmailRoute: typeof AuthForgotEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthOauthProviderCallbackRoute: typeof AuthOauthProviderCallbackRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotEmailRoute: AuthForgotEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthOauthProviderCallbackRoute: AuthOauthProviderCallbackRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainSettingsRouteRouteChildren {
  MainSettingsAIRoute: typeof MainSettingsAIRoute
  MainSettingsAboutRoute: typeof MainSettingsAboutRoute
  MainSettingsAppearanceRoute: typeof MainSettingsAppearanceRoute
  MainSettingsProfileRoute: typeof MainSettingsProfileRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
}

const MainSettingsRouteRouteChildren: MainSettingsRouteRouteChildren = {
  MainSettingsAIRoute: MainSettingsAIRoute,
  MainSettingsAboutRoute: MainSettingsAboutRoute,
  MainSettingsAppearanceRoute: MainSettingsAppearanceRoute,
  MainSettingsProfileRoute: MainSettingsProfileRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
}

const MainSettingsRouteRouteWithChildren =
  MainSettingsRouteRoute._addFileChildren(MainSettingsRouteRouteChildren)

interface MainRouteRouteChildren {
  MainSettingsRouteRoute: typeof MainSettingsRouteRouteWithChildren
  MainSplatRoute: typeof MainSplatRoute
  MainSelectAppRoute: typeof MainSelectAppRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainSettingsRouteRoute: MainSettingsRouteRouteWithChildren,
  MainSplatRoute: MainSplatRoute,
  MainSelectAppRoute: MainSelectAppRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AppIdSphereRouteRouteChildren {
  AppIdSphereIndexRoute: typeof AppIdSphereIndexRoute
  AppIdSphereChatChatIdRoute: typeof AppIdSphereChatChatIdRoute
}

const AppIdSphereRouteRouteChildren: AppIdSphereRouteRouteChildren = {
  AppIdSphereIndexRoute: AppIdSphereIndexRoute,
  AppIdSphereChatChatIdRoute: AppIdSphereChatChatIdRoute,
}

const AppIdSphereRouteRouteWithChildren =
  AppIdSphereRouteRoute._addFileChildren(AppIdSphereRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppIdRouteRoute: AppIdRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  AppIdSphereRouteRoute: AppIdSphereRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
