// Command genbindings 把 `internal/bridge/catalog.go` 里的方法 / 事件目录渲染成
// 页面侧消费的 TypeScript 文件。
//
// 用法（都在 apps/desktop 目录下跑，cwd 决定默认输出路径）：
//
//	go run ./cmd/genbindings              # 写文件
//	go run ./cmd/genbindings -check       # 只校验文件是否与目录一致（CI 用）
//
// 目录是唯一的真值：页面侧不再手写方法名（见 catalog.go 顶部说明）。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/nivo-team/dashboard/apps/desktop/internal/bridge"
)

const defaultOut = "../web/src/desktop/generated/bridge.gen.ts"

func main() {
	out := flag.String("out", defaultOut, "输出文件路径（相对当前目录）")
	check := flag.Bool("check", false, "只校验文件是否与目录一致，不写文件")
	flag.Parse()

	content, err := render()
	if err != nil {
		fail(err)
	}

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			fail(fmt.Errorf("读取 %s 失败（先跑一次 `pnpm desktop:bindings`）：%w", *out, err))
		}
		if !bytes.Equal(existing, content) {
			fail(fmt.Errorf("%s 与 internal/bridge/catalog.go 不一致；跑 `pnpm desktop:bindings` 重新生成", *out))
		}
		fmt.Printf("[genbindings] %s 已是最新\n", *out)
		return
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fail(fmt.Errorf("建目录失败：%w", err))
	}
	if err := os.WriteFile(*out, content, 0o644); err != nil {
		fail(fmt.Errorf("写 %s 失败：%w", *out, err))
	}
	fmt.Printf("[genbindings] 已生成 %s（%d 个方法 / %d 个事件）\n", *out, len(bridge.Methods), len(bridge.Events))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "[genbindings]", err)
	os.Exit(1)
}

// render 产出完整的 TS 文本。顺序按方法名 / 事件名排序，保证不同机器上结果一致。
func render() ([]byte, error) {
	methods := append([]bridge.Method(nil), bridge.Methods...)
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })

	events := append([]bridge.CatalogEvent(nil), bridge.Events...)
	sort.Slice(events, func(i, j int) bool { return events[i].Name < events[j].Name })

	if err := checkAliasCollisions(methods, events); err != nil {
		return nil, err
	}

	var b strings.Builder

	b.WriteString("// Code generated by `pnpm desktop:bindings` from apps/desktop/internal/bridge/catalog.go. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// 页面与桌面壳之间 bridge 的方法名 / 事件名与载荷类型，全部由 Go 侧目录生成 ——\n")
	b.WriteString("// 两侧的名字因此不可能各写一份而漂移。改方法：先改 catalog.go，再跑 `pnpm desktop:bindings`。\n")
	b.WriteString("//\n")
	b.WriteString("// 用法（低层收发在 `#/desktop/bridge`，别直接用它，别在这里加代码）：\n")
	b.WriteString("//\n")
	b.WriteString("//\timport { invoke, subscribe } from '#/desktop/bridge'\n")
	b.WriteString("//\tconst info = await invoke('core.info')\n")
	b.WriteString("//\tconst off = subscribe('theme:systemChanged', (data) => …)\n")
	b.WriteString("\n")

	// 具名类型别名
	for _, m := range methods {
		base := aliasBase(m.Name)
		writeAlias(&b, base+"Payload", m.Payload, m.Summary)
		writeAlias(&b, base+"Result", m.Result, m.Summary)
	}
	for _, e := range events {
		writeAlias(&b, aliasBase(e.Name)+"Payload", e.Payload, e.Summary)
	}

	// 方法表
	b.WriteString("/** 页面 → 壳：方法名 → 载荷 / 结果类型。 */\n")
	b.WriteString("export interface BridgeMethodMap {\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "  /** %s */\n", escapeComment(m.Summary))
		fmt.Fprintf(&b, "  %s: { payload: %s; result: %s }\n", quoteKey(m.Name), refType(aliasBase(m.Name)+"Payload", m.Payload), refType(aliasBase(m.Name)+"Result", m.Result))
	}
	b.WriteString("}\n\n")

	// 事件表
	b.WriteString("/** 壳 → 页面：事件名 → 载荷类型。 */\n")
	b.WriteString("export interface BridgeEventMap {\n")
	for _, e := range events {
		fmt.Fprintf(&b, "  /** %s */\n", escapeComment(e.Summary))
		fmt.Fprintf(&b, "  %s: %s\n", quoteKey(e.Name), refType(aliasBase(e.Name)+"Payload", e.Payload))
	}
	b.WriteString("}\n\n")

	// 运行时可枚举的名字（护栏 / 调试用）
	b.WriteString("/** 全部方法名（运行时可枚举，护栏与调试用）。 */\n")
	b.WriteString("export const BRIDGE_METHODS = [\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "  %s,\n", quoteKey(m.Name))
	}
	b.WriteString("] as const\n\n")

	b.WriteString("/** 全部事件名（运行时可枚举）。 */\n")
	b.WriteString("export const BRIDGE_EVENTS = [\n")
	for _, e := range events {
		fmt.Fprintf(&b, "  %s,\n", quoteKey(e.Name))
	}
	b.WriteString("] as const\n\n")

	b.WriteString("/** 方法名联合类型。 */\n")
	b.WriteString("export type BridgeMethodName = keyof BridgeMethodMap\n\n")
	b.WriteString("/** 事件名联合类型。 */\n")
	b.WriteString("export type BridgeEventName = keyof BridgeEventMap\n")

	return []byte(b.String()), nil
}

// checkAliasCollisions 提前查重 —— 名字不同但规范化后相同的两个条目会撞成一个类型名。
func checkAliasCollisions(methods []bridge.Method, events []bridge.CatalogEvent) error {
	seen := map[string]string{}
	register := func(kind, name string) error {
		base := aliasBase(name)
		if prev, ok := seen[base]; ok {
			return fmt.Errorf("别名冲突：%s 与 %s 都规范化为 %s", prev, kind+":"+name, base)
		}
		seen[base] = kind + ":" + name
		return nil
	}
	for _, m := range methods {
		if err := register("method", m.Name); err != nil {
			return err
		}
	}
	for _, e := range events {
		if err := register("event", e.Name); err != nil {
			return err
		}
	}
	return nil
}

// writeAlias 为一段类型表达式写一个具名别名；`void`（无载荷 / 无结果）跳过。
func writeAlias(b *strings.Builder, name, ts, summary string) {
	if isVoid(ts) {
		return
	}
	fmt.Fprintf(b, "/** %s */\n", escapeComment(summary))
	fmt.Fprintf(b, "export type %s = %s\n\n", name, strings.TrimRight(ts, "\n"))
}

// refType 引用写好的别名；void 直接内联。
func refType(alias, ts string) string {
	if isVoid(ts) {
		return "void"
	}
	return alias
}

func isVoid(ts string) bool {
	trimmed := strings.TrimSpace(ts)
	return trimmed == "" || trimmed == "void" || trimmed == "undefined"
}

// escapeComment 压掉换行，避免多行说明把 TS 注释撑破。
func escapeComment(text string) string {
	return strings.ReplaceAll(strings.TrimSpace(text), "\n", " ")
}

// quoteKey 用单引号包住名字（`core.info` / `shell:ready` 都不是合法裸标识符）。
func quoteKey(name string) string {
	return "'" + strings.ReplaceAll(name, "'", "\\'") + "'"
}

// aliasBase 把 `window.getBlurSupport` / `theme:systemChanged` 规范成 `WindowGetBlurSupport`。
func aliasBase(name string) string {
	var b strings.Builder
	upperNext := true
	for _, r := range name {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = true
			continue
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		}
		b.WriteRune(r)
	}
	if b.Len() == 0 {
		return "X"
	}
	// 首字符是数字时加前缀，保证是合法 TS 标识符
	first, _ := utf8.DecodeRuneInString(b.String())
	if unicode.IsDigit(first) {
		return "N" + b.String()
	}
	return b.String()
}
